CREATE TABLE IF NOT EXISTS Users (
	id SERIAL PRIMARY KEY,
	email VARCHAR(255) UNIQUE NOT NULL,
	name VARCHAR(100) UNIQUE NOT NULL,
	avatar_url TEXT,
	hash TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Oauth_Account (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE,
	provider VARCHAR(20) NOT NULL,
	provider_user_id VARCHAR(255) NOT NULL,
	access_token TEXT,
	refresh_token TEXT,
	token_expires_at TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(provider, provider_user_id)
);

CREATE TABLE IF NOT EXISTS Session_Account (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES Users(id) ON DELETE CASCADE,
	token VARCHAR(255) UNIQUE NOT NULL,
	expires_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);